name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to EC2
        run: |
          # Set up SSH key
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/treepz_website_github_rsa
          chmod 600 ~/.ssh/treepz_website_github_rsa

          # Transfer files to server
          rsync -avz --delete-after -e "ssh -o StrictHostKeyChecking=no" ./build/ $SSH_USERNAME@$SSH_HOST:/var/www/demo.treepz.com

          # Restart Next.js app
          ssh $SSH_USERNAME@$SSH_HOST "cd /var/www/demo.treepz.com && pm2 restart dev"

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
